---
driver:
  name: docker
  use_sudo: false
  #workaround for ubuntu 18.04
  #provision_command: "mkdir -p /run/sshd"

provisioner:
  name: shell

verifier:
  name: inspec

platforms:
  - name: ubuntu
    driver_config:
      image: achuchulev/packer-nginx:nginx-0.1
      platform: ubuntu
      remove_images: true

suites:
- name: default
  verifier:
      inspec_tests:
        - test/integration/default
